// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RoyalFlora.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260110103153_EenFotoPerProduct")]
    partial class EenFotoPerProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bedrijf", b =>
                {
                    b.Property<int>("KVK")
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("BedrijfNaam")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int?>("Oprichter")
                        .HasColumnType("int");

                    b.Property<string>("Postcode")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("KVK");

                    b.HasIndex("Oprichter");

                    b.ToTable("Bedrijf");
                });

            modelBuilder.Entity("Foto", b =>
                {
                    b.Property<int>("IdFoto")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("FotoPath")
                        .HasColumnType("text");

                    b.HasKey("IdFoto", "IdProduct");

                    b.HasIndex("IdProduct")
                        .IsUnique();

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("Gebruiker", b =>
                {
                    b.Property<int>("IdGebruiker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGebruiker"));

                    b.Property<string>("AchterNaam")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Adress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("E-mail");

                    b.Property<int?>("KVK")
                        .HasColumnType("int");

                    b.Property<string>("Postcode")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefoonnummer")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("VoorNaam")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdGebruiker");

                    b.HasIndex("KVK");

                    b.HasIndex("Rol");

                    b.ToTable("Gebruiker");
                });

            modelBuilder.Entity("Locatie", b =>
                {
                    b.Property<int>("IdLocatie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocatie"));

                    b.Property<string>("locatieNaam")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("IdLocatie");

                    b.ToTable("Locatie");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<int?>("Aantal")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Koper")
                        .HasColumnType("int");

                    b.Property<int?>("Leverancier")
                        .HasColumnType("int");

                    b.Property<string>("Locatie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MinimumPrijs")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ProductBeschrijving")
                        .HasColumnType("text");

                    b.Property<string>("ProductNaam")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<decimal?>("StartPrijs")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("verkoopPrijs")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdProduct");

                    b.HasIndex("Koper");

                    b.HasIndex("Leverancier");

                    b.HasIndex("Status");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Rol", b =>
                {
                    b.Property<int>("IdRollen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRollen"));

                    b.Property<string>("RolNaam")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("IdRollen");

                    b.ToTable("Rollen");

                    b.HasData(
                        new
                        {
                            IdRollen = 1,
                            RolNaam = "Aanvoerder"
                        },
                        new
                        {
                            IdRollen = 2,
                            RolNaam = "Inkoper"
                        },
                        new
                        {
                            IdRollen = 3,
                            RolNaam = "Veilingmeester"
                        });
                });

            modelBuilder.Entity("Status", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatus"));

                    b.Property<string>("Beschrijving")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("IdStatus");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            IdStatus = 1,
                            Beschrijving = "Geregistreerd"
                        },
                        new
                        {
                            IdStatus = 2,
                            Beschrijving = "Ingepland"
                        },
                        new
                        {
                            IdStatus = 3,
                            Beschrijving = "Geveild"
                        },
                        new
                        {
                            IdStatus = 4,
                            Beschrijving = "Verkocht"
                        },
                        new
                        {
                            IdStatus = 5,
                            Beschrijving = "Gepauzeerd"
                        });
                });

            modelBuilder.Entity("Veiling", b =>
                {
                    b.Property<int>("Locatie_idLocatie")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Products_IdProduct")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("datum")
                        .HasColumnType("date");

                    b.Property<string>("ordernummer")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Locatie_idLocatie", "Products_IdProduct");

                    b.HasIndex("Products_IdProduct");

                    b.ToTable("Veiling");
                });

            modelBuilder.Entity("Bedrijf", b =>
                {
                    b.HasOne("Gebruiker", "OprichterNavigation")
                        .WithMany("BedrijvenOprichter")
                        .HasForeignKey("Oprichter")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OprichterNavigation");
                });

            modelBuilder.Entity("Foto", b =>
                {
                    b.HasOne("Product", "ProductNavigation")
                        .WithOne("Foto")
                        .HasForeignKey("Foto", "IdProduct")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("Gebruiker", b =>
                {
                    b.HasOne("Bedrijf", "BedrijfNavigation")
                        .WithMany("Gebruikers")
                        .HasForeignKey("KVK")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Rol", "RolNavigation")
                        .WithMany("Gebruikers")
                        .HasForeignKey("Rol")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BedrijfNavigation");

                    b.Navigation("RolNavigation");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("Gebruiker", "KoperNavigation")
                        .WithMany("ProductsKoper")
                        .HasForeignKey("Koper")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Bedrijf", "LeverancierNavigation")
                        .WithMany("Products")
                        .HasForeignKey("Leverancier")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Status", "StatusNavigation")
                        .WithMany("Products")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("KoperNavigation");

                    b.Navigation("LeverancierNavigation");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("Veiling", b =>
                {
                    b.HasOne("Locatie", "LocatieNavigation")
                        .WithMany("Veilingen")
                        .HasForeignKey("Locatie_idLocatie")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Product", "ProductNavigation")
                        .WithMany("Veilingen")
                        .HasForeignKey("Products_IdProduct")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LocatieNavigation");

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("Bedrijf", b =>
                {
                    b.Navigation("Gebruikers");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Gebruiker", b =>
                {
                    b.Navigation("BedrijvenOprichter");

                    b.Navigation("ProductsKoper");
                });

            modelBuilder.Entity("Locatie", b =>
                {
                    b.Navigation("Veilingen");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("Foto");

                    b.Navigation("Veilingen");
                });

            modelBuilder.Entity("Rol", b =>
                {
                    b.Navigation("Gebruikers");
                });

            modelBuilder.Entity("Status", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
